MODULE PARAMETERS
  IMPLICIT NONE
  INTEGER, PARAMETER :: dp=selected_real_kind(15,300)
  INTEGER, PARAMETER :: NUMBER_OF_FUNCTIONALS = 20
  INTEGER, PARAMETER :: BOOTSTRAP_MULTIPLIER = 1
  INTEGER, PARAMETER :: BOOTSTRAP_ITERATIONS = 5
END MODULE PARAMETERS
 
